{'name': 'ESI - Odoo ALL Financial Reports (BS,P&L,GL,Trial Balance)(PDF/EXCEL)',
 'version': '13.0.0.1',
 'author': 'ESI - Especialistas en Sistemas Integrados',
 'website': 'https://esibolivia.store',
 'category': 'Accounting',
 'summary': 'Apps for print all Accounting Reports in excel Accounting reports Balance Sheet excel report General '
            'Ledger excel report Trial Balance excel report Profit & Loss excel report financial excel report '
            'accounting xls report financial xls report',
 'description': ' \n'
                '\n'
                '\n'
                '        print General Ledger Report\n'
                '        print Trial Balance Report\n'
                '        Odoo12 Financial Reports  \n'
                '        Odoo 12 Financial Reports PDF \n'
                '        Odoo 12 accounting Reports pdf \n'
                '        Financial Reports in Odoo v12\n'
                '        Financial Reports in Odoo 12\n'
                '        accounting Reports in Odoo v12\n'
                '        odoo12 accounting reports\n'
                '        Accounting report odoo12\n'
                '        odoo12 reports\n'
                '        Odoo12 Accounting PDF reports\n'
                '        Odoo12 financial pdf reports\n'
                '\n'
                '        print General Ledger excel Report odoo12\n'
                '        print Odoo12 Trial Balance Report excel\n'
                '        Odoo12 Financial Excel Reports  \n'
                '        Odoo 12 Financial excel Reports \n'
                '        Odoo 12 accounting excel Reports\n'
                '        Odoo12 accounting reports in excel\n'
                '        Odoo12 accounting Reports in excel\n'
                '        Odoo12 Financial Reports in excel\n'
                '        Odoo 12 Financial xls Reports \n'
                '        Odoo 12 accounting xls Reports\n'
                '        Odoo12 accounting reports in xls\n'
                '        Odoo12 accounting Reports in xls\n'
                '        Odoo12 Financial Reports in xls  \n'
                '\n'
                '        Excel Financial Reports in Odoo v12\n'
                '        Financial excel Reports in Odoo 12\n'
                '        accounting xls Reports in Odoo v12\n'
                '        odoo12 accounting excel reports\n'
                '        Excel Accounting report odoo12\n'
                '        XLS odoo12 reports\n'
                '        Odoo12 Accounting Excel reports\n'
                '        Odoo12 financial xls reports\n'
                '\n'
                '        Print Accounting Reports\n'
                '        With the help of this module you can print report for Accounting\n'
                '        print General Ledger Report\n'
                '        print Trial Balance Report\n'
                '        print Profit & Loss Report\n'
                '        print Balance Sheet Report\n'
                '        print General Ledger Excel Report\n'
                '        print Trial Balance Excel Report\n'
                '        print Profit & Loss Excel Report\n'
                '        print Balance Sheet Excel Report\n'
                '        print General Ledger Report\n'
                '        print Trial Balance Report\n'
                '        print Profit & Loss Report\n'
                '        print Balance Sheet Report\n'
                '        All Accounting reports\n'
                '        Accounting XLS report\n'
                '        Accounting NIIF reports\n'
                '        Account balance sheet reports\n'
                '        Account General Ledger Reports\n'
                '        Account Trial balance reports\n'
                '        Account profit and loss reports\n'
                '        P&L Excel Report\n'
                '        Excel Financial Statements\n'
                '        Excel Financial reports\n'
                '        Financial Statements in Excel\n'
                '        Financial reports in Excel\n'
                '        Xls Financial Statements\n'
                '        XLS Financial reports\n'
                '        Financial Statements in XLS\n'
                '        Financial reports in XLS\n'
                '        Financial Statements Export\n'
                '        Export Accounting Reports\n'
                '        Accounting Statement Excel\n'
                '        Account statement excel\n'
                '        Excel Accounting report\n'
                '        Business statement excel\n'
                '        profit and loss excel report\n'
                '        profit and loss report\n'
                '        Download Excel report,\n'
                '        Download Accounting report\n'
                '        Excel Accounting statement\n'
                '        All Financial Excel Reports\n'
                '        All Financial(BS,GL,P&L,TB) Excel Reports\n'
                '        BS,GL,P&L,TB Excel Reports\n'
                '        Accounting Reports\n'
                '        \n'
                "Rapports Excel de comptabilité d'impression\n"
                "        Avec l'aide de ce module, vous pouvez imprimer le rapport Excel pour la comptabilité\n"
                '        print General Ledger Report En format de fichier Excel\n'
                '        print Rapport de balance de vérification En format de fichier Excel\n'
                '        print Rapport sur les profits et les pertes En format de fichier Excel\n'
                '        imprimer Rapport de bilan En format de fichier Excel\n'
                '        imprimer Rapport sur le grand livre général\n'
                '        imprimer le rapport Excel de la balance de vérification\n'
                '        imprimer Rapport Excel sur les profits et les pertes\n'
                '        imprimer Bilan Excel Rapport\n'
                '        imprimer Rapport du grand livre général XLS\n'
                "        imprimer Rapport d'essai Balance XLS\n"
                '        imprimer Rapport sur les profits et les pertes XLS\n'
                '        imprimer le bilan Rapport XLS\n'
                '        Tous les rapports de comptabilité au format Excel\n'
                '        Rapport XLS de comptabilité\n'
                '        Rapport Excel pour la comptabilité\n'
                '        Rapports NIIF comptables\n'
                '        Rapport BS Excel\n'
                '        GL excel Rapport\n'
                '        Rapport TB Excel\n'
                '        Rapport P & L Excel\n'
                '        États financiers Excel\n'
                '        Rapports financiers Excel\n'
                '        États financiers dans Excel\n'
                '        Rapports financiers dans Excel\n'
                '        États financiers Xls\n'
                '        Rapports financiers XLS\n'
                '        États financiers dans XLS\n'
                '        Rapports financiers dans XLS\n'
                '        États financiers Export\n'
                "        Rapports de comptabilité d'exportation\n"
                '        Déclaration comptable Excel\n'
                '        Relevé de compte Excel\n'
                '        Rapport de comptabilité Excel\n'
                "        Déclaration d'affaires excel\n"
                '        rapport Excel sur les profits et pertes\n'
                '        rapport de profits et pertes\n'
                '        Télécharger le rapport Excel,\n'
                '        Télécharger le rapport de comptabilité\n'
                '        Déclaration de comptabilité Excel\n'
                '        Tous les rapports Excel financiers\n'
                '        Tous les rapports Excel financiers (BS, GL, P & L, TB)\n'
                '        BS, GL, P et L, rapports TB Excel\n'
                '        Rapports de comptabilité\n'
                '        Imprimir informes de contabilidad de Excel\n'
                '        Con la ayuda de este módulo, puede imprimir el informe de Excel para Contabilidad\n'
                '        print Informe del Libro mayor en formato de archivo excel\n'
                '        print Informe de Balance de Prueba en formato de archivo excel\n'
                '        print Informe de pérdidas y ganancias en formato de archivo excel\n'
                '        imprimir informe del balance en formato de archivo excel\n'
                '        imprimir General Ledger Excel Report\n'
                '        imprimir Balance de prueba Excel Informe\n'
                '        print Informe de Excel de Pérdidas y Ganancias\n'
                '        imprimir Balance Excel Informe de Excel\n'
                '        imprimir General Ledger XLS Report\n'
                '        imprimir el informe de Trial Balance XLS\n'
                '        print Informe de ganancias y pérdidas XLS\n'
                '        imprimir Balance XLS Informe\n'
                '        Todos los informes contables en formato Excel\n'
                '        Informe XLS de contabilidad\n'
                '        Informe Excel para contabilidad\n'
                '        Informes NIIF de contabilidad\n'
                '        Informe BS Excel\n'
                '        GL excel Informe\n'
                '        Informe de TB Excel\n'
                '        P & L Excel Report\n'
                '        Estados financieros Excel\n'
                '        Informes financieros de Excel\n'
                '        Estados financieros en Excel\n'
                '        Informes financieros en Excel\n'
                '        Xls Estados Financieros\n'
                '        Informes financieros XLS\n'
                '        Estados financieros en XLS\n'
                '        Informes financieros en XLS\n'
                '        Estados financieros Exportación\n'
                '        Exportar informes contables\n'
                '        Declaración contable Excel\n'
                '        Declaración de cuenta excel\n'
                '        Informe contable de Excel\n'
                '        Declaración comercial excelente\n'
                '        informe de pérdidas y ganancias de Excel\n'
                '        informe de pérdidas y ganancias\n'
                '        Descargar el informe de Excel,\n'
                '        Descargar informe de contabilidad\n'
                '        Declaración contable de Excel\n'
                '        Todos los informes financieros de Excel\n'
                '        Todos los informes financieros de Excel (BS, GL, P y L, TB)\n'
                '        BS, GL, P & L, TB Excel Reports\n'
                '        Informes de contabilidad\n'
                '        Drucken Sie Excel-Berichte\n'
                '        Mit Hilfe dieses Moduls können Sie Excel-Berichte für das Rechnungswesen drucken\n'
                '        Hauptbuchbericht im Excel-Dateiformat drucken\n'
                '        Testbericht drucken Im Excel-Dateiformat\n'
                '        Drucken Gewinn- und Verlustbericht Im Excel-Dateiformat\n'
                '        Druck Bilanz Bericht Im Excel-Dateiformat\n'
                '        Hauptbuch Excel-Bericht drucken\n'
                '        Testbericht Excel-Bericht drucken\n'
                '        Drucken Gewinn und Verlust Excel-Bericht\n'
                '        Excel-Bericht über Bilanz drucken\n'
                '        Drucken Sie den Hauptbuch XLS Report\n'
                '        Drucken Sie den Testbericht von Balance XLS\n'
                '        Drucken Sie Gewinn und Verlust XLS Bericht\n'
                '        Druck Bilanz XLS Bericht\n'
                '        Alle Accounting-Berichte im Excel-Format\n'
                '        Buchhaltungs-XLS-Bericht\n'
                '        Excel-Bericht für die Buchhaltung\n'
                '        Accounting NIIF-Berichte\n'
                '        BS Excel-Bericht\n'
                '        GL Excel Bericht\n'
                '        TB Excel Bericht\n'
                '        P & L Excel Bericht\n'
                '        Excel-Finanzberichte\n'
                '        Excel Finanzberichte\n'
                '        Jahresabschluss in Excel\n'
                '        Finanzberichte in Excel\n'
                '        Xls Finanzberichte\n'
                '        XLS Finanzberichte\n'
                '        Jahresabschlüsse in XLS\n'
                '        Finanzberichte in XLS\n'
                '        Finanzberichte Export\n'
                '        Buchhaltungsberichte exportieren\n'
                '        Kontoauszug Excel\n'
                '        Kontoauszug Excel\n'
                '        Excel-Buchhaltungsbericht\n'
                '        Geschäftsaussage Excel\n'
                '        Gewinn und Verlust Excel-Bericht\n'
                '        Gewinn- und Verlustrechnung\n'
                '        Excel-Bericht herunterladen,\n'
                '        Download Buchhaltungsbericht\n'
                '        Excel-Kontoauszug\n'
                '        Alle finanziellen Excel-Berichte\n'
                '        Alle finanziellen (BS, GL, P & L, TB) Excel-Berichte\n'
                '        BS, GL, P & L, TB Excel Berichte\n'
                '        Buchhaltungsberichte\n'
                '\n'
                'Relatórios de Excel de contabilidade de impressão\n'
                '        Com a ajuda deste módulo você pode imprimir um relatório de excel para contabilidade\n'
                '        imprimir relatório do razão geral no formato de arquivo excel\n'
                '        imprimir Relatório do Balancete no formato de arquivo excel\n'
                '        imprimir Relatório de lucros e perdas No formato de arquivo excel\n'
                '        imprimir Relatório do Balanço Em formato de arquivo excel\n'
                '        imprimir relatório geral do Excel no razão\n'
                '        imprimir relatório do Excel no balancete\n'
                '        imprimir Relatório Excel de Perda e Perda\n'
                '        Imprimir Balanço Excel Report\n'
                '        imprimir Relatório do Razão Geral XLS\n'
                '        imprimir relatório do balancete de avaliação XLS\n'
                '        imprimir Relatório XLS de Lucros e Perdas\n'
                '        Imprimir Balanço XLS Report\n'
                '        Todo o relatório de Contabilidade no formato Excel\n'
                '        Relatório de contabilidade XLS\n'
                '        Relatório do Excel para contabilidade\n'
                '        Relatórios contábeis da NIIF\n'
                '        Relatório do BS Excel\n'
                '        Relatório do Excel\n'
                '        Relatório do TB Excel\n'
                '        Relatório Excel P & L\n'
                '        Demonstrações Financeiras do Excel\n'
                '        Relatórios financeiros do Excel\n'
                '        Demonstrações Financeiras no Excel\n'
                '        Relatórios financeiros no Excel\n'
                '        Demonstrações Financeiras Xls\n'
                '        Relatórios financeiros XLS\n'
                '        Demonstrações Financeiras em XLS\n'
                '        Relatórios financeiros no XLS\n'
                '        Exportação de Demonstrações Financeiras\n'
                '        Relatórios contábeis de exportação\n'
                '        Demonstração Contábil Excel\n'
                '        Extrato da conta excel\n'
                '        Relatório de contabilidade do Excel\n'
                '        Declaração de negócios excel\n'
                '        relatório de excel de lucros e perdas\n'
                '        relatório de lucros e perdas\n'
                '        Baixe o relatório do Excel,\n'
                '        Download do relatório contábil\n'
                '        Instrução de contabilidade do Excel\n'
                '        Todos os relatórios financeiros do Excel\n'
                '        Todos os relatórios financeiros (BS, GL, P & L, TB) do Excel\n'
                '        Relatórios BS, GL, P & L, TB Excel\n'
                '        Relatórios contábeis\n'
                '        Drucken Sie Excel-Berichte\n'
                '        Mit Hilfe dieses Moduls können Sie Excel-Berichte für das Rechnungswesen drucken\n'
                '        Hauptbuchbericht im Excel-Dateiformat drucken\n'
                '        Testbericht drucken Im Excel-Dateiformat\n'
                '        Drucken Gewinn- und Verlustbericht Im Excel-Dateiformat\n'
                '        Druck Bilanz Bericht Im Excel-Dateiformat\n'
                '        Hauptbuch Excel-Bericht drucken\n'
                '        Testbericht Excel-Bericht drucken\n'
                '        Drucken Gewinn und Verlust Excel-Bericht\n'
                '        Excel-Bericht über Bilanz drucken\n'
                '        Drucken Sie den Hauptbuch XLS Report\n'
                '        Drucken Sie den Testbericht von Balance XLS\n'
                '        Drucken Sie Gewinn und Verlust XLS Bericht\n'
                '        Druck Bilanz XLS Bericht\n'
                '        Alle Accounting-Berichte im Excel-Format\n'
                '        Buchhaltungs-XLS-Bericht\n'
                '        Excel-Bericht für die Buchhaltung\n'
                '        Accounting NIIF-Berichte\n'
                '        BS Excel-Bericht\n'
                '        GL Excel Bericht\n'
                '        TB Excel Bericht\n'
                '        P & L Excel Bericht\n'
                '        Excel-Finanzberichte\n'
                '        Excel Finanzberichte\n'
                '        Jahresabschluss in Excel\n'
                '        Finanzberichte in Excel\n'
                '        Xls Finanzberichte\n'
                '        XLS Finanzberichte\n'
                '        Jahresabschlüsse in XLS\n'
                '        Finanzberichte in XLS\n'
                '        Finanzberichte Export\n'
                '        Buchhaltungsberichte exportieren\n'
                '        Kontoauszug Excel\n'
                '        Kontoauszug Excel\n'
                '        Excel-Buchhaltungsbericht\n'
                '        Geschäftsaussage Excel\n'
                '        Gewinn und Verlust Excel-Bericht\n'
                '        Gewinn- und Verlustrechnung\n'
                '        Excel-Bericht herunterladen,\n'
                '        Download Buchhaltungsbericht\n'
                '        Excel-Kontoauszug\n'
                '        Alle finanziellen Excel-Berichte\n'
                '        Alle finanziellen (BS, GL, P & L, TB) Excel-Berichte\n'
                '        BS, GL, P & L, TB Excel Berichte\n'
                '        Buchhaltungsberichte\n'
                '        \n'
                '    ',
 'depends': ['esi_bi_financial_pdf_reports'],
 'data': ['wizard/inherited_balancesheet_view.xml',
          'wizard/inherited_generalledger_view.xml',
          'wizard/inherited_trialbalance_view.xml',
          'wizard/inherited_cash_flow_view.xml',
          'wizard/excel_report.xml'],
 'price': 5.99,
 'currency': 'EUR',
 'installable': True,
 'auto_install': False,
 'live_test_url': 'https://youtu.be/CdzmqMt9NfU',
 'images': ['static/description/Banner.png'],
 'maintainer': 'ESI - Especialistas en Sistemas Integrados'}
